version = 1

[[annotations]]
path = [
    "poetry.lock",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = 'renovate.json'
SPDX-FileCopyrightText = "Greg Back <git@gregback.net>"
SPDX-License-Identifier = "CC0-1.0"
